#!/bin/bash

# Author:  clif-s
# Course:  ICT Skills - HDip in Computer Science 2016
# Subject: Computer Systems - Shell Programming Assignment

# Program Description:

# This is the Email Customer menu for the shell programming assignment.

source ExampleRepos.sh      # Imports the ExampleRepos.sh function repository.

while :
	do
	clear
	echo "$(tput setaf 2)$(tput bold)Email Customer(s)$(tput sgr 0) - Please choose one of the following:"
	echo ""
	echo "      1. Email a Customer"
	echo "      M. Main Menu"
	echo ""
	echo -n "Please select : [1, or M] "
	
        # Returns an error message and instructions to the user
        # if CustomerDetails does not exist. This then returns
        # the user to the main menu.

        if [[ ! -f CustomerDetails ]]; then
        echo    ""
        echo    ""
        echo    "$(tput setaf 1)ERROR$(tput sgr 0) CustomerDetails can not be found! $(tput setaf 1)ERROR$(tput sgr 0)"
        echo    "      Please add at least one customer!"
        echo    ""
        echo -n "      Press [enter] key to return to main menu"
        read enterKey
        echo    ""
        echo -n "      Returning to main menu..."
        sleep 1.92
        ./Menu; exit 1
        fi

	read sel
	case $sel in

		1) 		email_customer     # runs the fuction contained in ExampleRepos.sh
				;;

		m | M) 	./Menu; exit 1
				;;

		*) 		echo    ""
		   		echo    "$sel is invalid. Please select [1, or M]";
		   		echo -n "Press [enter] key to continue...";
		   		read enterKey
		   		;;
	esac
done